### ISSUE TITLE
Add explicit launch file to interface with Kimera-VIO

### ISSUE THREAD

**Issue by ToniRV** [MIT-SPARK/Kimera-Semantics#12]
Currently, the launch file provided can be easily modified to connect with Kimera-VIO, but perhaps provide another launch file for simplicity (running in Euroc).
https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/46

**Comment by cclo-astri** [comment]
Hi,

Any updates about this request?

Thanks.

**Comment by ToniRV** [comment]
Done!
