### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by FrozenSmile** [MIT-SPARK/Kimera-Semantics#20]
Thanks for your great work！ 
My first compiling failed because of the same error in issue #10 and #15，I checked out  7e985e9 and  succeed to compile but some errors still occurred when I roslaunch.

I just change the "bag file" to the path of rosbag.  
I execute `roslaunch kimera_semantics_ros kimera_semantics.launch play_bag:=true` and the rosbag played properly but some errors ouccrred as this:

`[ERROR] Failed to load nodelet [/cloudify] of type [depth_image_proc/point_cloud_xyzrgb] even after refreshing the cache.`

`[cloudify-4] process has died [pid 123603,exit code 255, cmd /opt/ros/kinetic/lib/nodelet load depth_image_proc/point_cloud_xyzrgb noodelet_manager -no-bond rgb/camera_info:=/tesse/left_cam/camera_info rgb/image_rect_color:=/tesse/segmentation/image_raw depth_registered/image_rect:=/teese/depth/image_raw depth...`

'![image](https://user-images.githubusercontent.com/30323238/77231200-68942700-6bd4-11ea-9b70-d6d4b5af253b.png)'

'![image](https://user-images.githubusercontent.com/30323238/77231217-8b264000-6bd4-11ea-88c2-1440537096a3.png)'

![image](https://user-images.githubusercontent.com/30323238/77231812-3be20e80-6bd8-11ea-956d-d02c38e73bb1.png)

Nothing but a moving line in my rviz. I put the error picture to show you.It looks like the same error in #10 and #13  , but I don't understand how they fixed it. By the way，I use the new rosbag you updated in the usage, so the answer in #13 didn't help me .

I guess it's the problem about node name or pkg name so I modify the launch file as the last merge, but the error still exists. 

I'm a green hand in SLAM and lack for experience, please give me some suggestion to fix errors if you can, thank you.

**Comment by ToniRV** [comment]
Hi @FrozenSmile,

Thanks for the report!
As noted in #15 , try:
```
sudo apt-get install ros-melodic-depth-image-proc
```
Change melodic for your ROS distribution (i.e. kinetic etc)

**Comment by FrozenSmile** [comment]
> sudo apt-get install ros-melodic-depth-image-proc
Thanks a lot for your answer ! It works immediately!
