### ISSUE TITLE
Installation and Demo

### ISSUE THREAD

**Issue by YJonmo** [MIT-SPARK/Kimera-Semantics#22]
Hi Toni,

Sorry for bothering you again.

On both Ubuntu 16 and 18 I cannot get the demo running. I did all the steps in the installation. 
But I get below image which seems there is an error in installation and demo. I put the images at the end.
Just a tiny hint, I guess in the readme this line should change

Download the demo rosbag (click here to download) and save it in: ./kimera_semantics_ros/rosbag/kimera_semantics_demo.bag

to

Download the demo rosbag (click here to download) and save it in: ./kimera_semantics_ros/rosbags/kimera_semantics_demo.bag

Installation errors:

![Screenshot from 2020-03-29 16-33-21](https://user-images.githubusercontent.com/12040950/77842912-0db58d80-71db-11ea-8a38-09f21e77687a.png)

Demo:

![Screenshot from 2020-03-29 16-27-27](https://user-images.githubusercontent.com/12040950/77842916-18702280-71db-11ea-8598-228bdc0ce569.png)

**Comment by ToniRV** [comment]
Hi @YJonmo , please check https://github.com/MIT-SPARK/Kimera-Semantics/issues/15
I'm still working on this.

**Comment by ToniRV** [comment]
Ok, so I have done the necessary changes in Voxblox, now it should be a matter of waiting for the PR to be merged in Voxblox (or use my fork).

https://github.com/ethz-asl/voxblox/pull/317
