### ISSUE TITLE
No mesh published using own rosbags.

### ISSUE THREAD

**Issue by alandszhang** [MIT-SPARK/Kimera-Semantics#31]
Hi, @ToniRV,

Thanks for your impressive work. However, there exists a error showed as the followings when I used my own rosbag generated by RGB-D camera. In the meantime, there seems no mesh published by the nodes. Do you have any idea about the reasons? Outputs of the terminal show as follows.

dszhang@dszhang-hasee:~$ roslaunch kimera_semantics_ros kimera_semantics_mynteye.launch play_bag:=true metric_semantic_reconstruction:=false
... logging to /home/dszhang/.ros/log/ea3a07da-b6dd-11ea-82b1-b46921c40905/roslaunch-dszhang-hasee-2946.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dszhang-hasee:37799/

SUMMARY
========

CLEAR PARAMETERS
 * /kimera_semantics_node/

PARAMETERS
 * /cloudify/queue_size: 20
 * /kimera_semantics_node/color_mode: lambert_color
 * /kimera_semantics_node/dynamic_semantic_labels: [20]
 * /kimera_semantics_node/enable_icp: False
 * /kimera_semantics_node/icp_iterations: 10
 * /kimera_semantics_node/max_ray_length_m: 5
 * /kimera_semantics_node/mesh_filename: /home/dszhang/cat...
 * /kimera_semantics_node/method: fast
 * /kimera_semantics_node/min_time_between_msgs_sec: 0.2
 * /kimera_semantics_node/publish_pointclouds: False
 * /kimera_semantics_node/semantic_color_mode: semantic
 * /kimera_semantics_node/semantic_label_2_color_csv_filepath: /home/dszhang/cat...
 * /kimera_semantics_node/semantic_measurement_probability: 0.8
 * /kimera_semantics_node/sensor_frame: left_cam
 * /kimera_semantics_node/slice_level: 1.0
 * /kimera_semantics_node/tsdf_voxel_size: 0.05
 * /kimera_semantics_node/tsdf_voxels_per_side: 16
 * /kimera_semantics_node/update_mesh_every_n_sec: 0.1
 * /kimera_semantics_node/use_const_weight: False
 * /kimera_semantics_node/use_freespace_pointcloud: False
 * /kimera_semantics_node/use_tf_transforms: True
 * /kimera_semantics_node/verbose: True
 * /kimera_semantics_node/voxel_carving_enabled: True
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /use_sim_time: True

NODES
  /
    cloudify (nodelet/nodelet)
    kimera_semantics_node (voxblox_ros/tsdf_server)
    nodelet_manager (nodelet/nodelet)
    player (rosbag/play)

ROS_MASTER_URI=http://localhost:11311

process[player-1]: started with pid [2962]
process[nodelet_manager-2]: started with pid [2963]
process[cloudify-3]: started with pid [2964]
process[kimera_semantics_node-4]: started with pid [2965]
[ INFO] [1593087486.269896728]: Loading nodelet /cloudify of type depth_image_proc/point_cloud_xyzrgb to manager nodelet_manager with the following remappings:
[ INFO] [1593087486.270531303]: /depth_registered/image_rect -> /tesse/depth/image_raw
[ INFO] [1593087486.270544880]: /depth_registered/points -> /semantic_pointcloud
[ INFO] [1593087486.270551788]: /rgb/camera_info -> /tesse/left_cam/camera_info
[ INFO] [1593087486.270559571]: /rgb/image_rect_color -> /tesse/left_cam/image_raw
[ INFO] [1593087486.271091712]: Opening /home/dszhang/catkin_ws/src/Kimera-Semantics/kimera_semantics_ros/rosbags/mynteye_modified.bag
[ INFO] [1593087486.272007155]: waitForService: Service [/nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1593087486.286348887]: Initializing nodelet with 12 worker threads.
[ INFO] [1593087486.292622767]: waitForService: Service [/nodelet_manager/load_nodelet] is now available.

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
[ INFO] [1593087486.620226365, 1593060801.403045742]: Updating mesh.937   Delay: 0.00 
[ INFO] [1593087486.621326165, 1593060801.403045742]: Updating mesh.
[ INFO] [1593087486.753323221, 1593060801.509214950]: Updating mesh.937               
[ INFO] [1593087486.804753881, 1593060801.610383887]: Updating mesh.937               
[ INFO] [1593087486.860478760, 1593060801.720948987]: Updating mesh.937               
[ INFO] [1593087486.900017800, 1593060801.803128798]: Updating mesh.937               
[ INFO] [1593087486.950813028, 1593060801.903886334]: Updating mesh.937               
[ INFO] [1593087487.001038490, 1593060802.004558130]: Updating mesh.937               
[ INFO] [1593087487.051540943, 1593060802.105705186]: Updating mesh.937               
[ INFO] [1593087487.104106465, 1593060802.210582859]: Updating mesh.937               
[ INFO] [1593087487.154696987, 1593060802.312643781]: Updating mesh.937               
[ INFO] [1593087487.206116676, 1593060802.415652547]: Updating mesh.937               
[ INFO] [1593087487.256463844, 1593060802.516329599]: Updating mesh.937               
[ INFO] [1593087487.307124325, 1593060802.616994327]: Updating mesh.937               
[ INFO] [1593087487.358768241, 1593060802.721852264]: Updating mesh.937               
[ INFO] [1593087487.400878166, 1593060802.804243945]: Updating mesh.937               
[ INFO] [1593087487.451027132, 1593060802.906565460]: Updating mesh.937               
[ INFO] [1593087487.502699627, 1593060803.007689365]: Updating mesh.937               
[ INFO] [1593087487.552320577, 1593060803.108372618]: Updating mesh.937               
[ INFO] [1593087487.603224302, 1593060803.209191272]: Updating mesh.937               
[ INFO] [1593087487.654615437, 1593060803.313143269]: Updating mesh.937               
[ INFO] [1593087487.705218050, 1593060803.414191091]: Updating mesh.937               
[ INFO] [1593087487.756617990, 1593060803.515178603]: Updating mesh.937               
[ INFO] [1593087487.806508470, 1593060803.616220652]: Updating mesh.937               
[ INFO] [1593087487.850651271, 1593060803.703852692]: Updating mesh.937               
[ INFO] [1593087487.901159005, 1593060803.805402872]: Updating mesh.937               
[ INFO] [1593087487.952469648, 1593060803.908715577]: Updating mesh.937               
[ INFO] [1593087488.005727597, 1593060804.014972377]: Updating mesh.937               
[ INFO] [1593087488.057244973, 1593060804.116320700]: Updating mesh.937               
[ INFO] [1593087488.110493042, 1593060804.217189994]: Updating mesh.937               
[ INFO] [1593087488.158481066, 1593060804.319094223]: Updating mesh.937               
[ INFO] [1593087488.208412417, 1593060804.419893042]: Updating mesh.937               
[ERROR] [1593087488.228991836, 1593060804.460135583]: Input pointcloud queue getting too long! Dropping some pointclouds. Either unable to look up transform timestamps or the processing is taking too long.
[ INFO] [1593087488.258507466, 1593060804.520723962]: Updating mesh.937               
[ INFO] [1593087488.309400808, 1593060804.621719490]: Updating mesh.937               
[ INFO] [1593087488.359874881, 1593060804.722912579]: Updating mesh.937               
[ INFO] [1593087488.400330778, 1593060804.803589567]: Updating mesh.937               
[ INFO] [1593087488.450376393, 1593060804.905046762]: Updating mesh.937               
[ INFO] [1593087488.501999042, 1593060805.007730969]: Updating mesh.937               
[ INFO] [1593087488.553064135, 1593060805.108592523]: Updating mesh.937               
[ INFO] [1593087488.604023663, 1593060805.209585357]: Updating mesh.937               
[ INFO] [1593087488.654118739, 1593060805.310685188]: Updating mesh.937               
[ INFO] [1593087488.704120261, 1593060805.411497323]: Updating mesh.937               
[ INFO] [1593087488.755074481, 1593060805.512643616]: Updating mesh.937               
[ INFO] [1593087488.805880099, 1593060805.614183568]: Updating mesh.937               
[ INFO] [1593087488.856641021, 1593060805.715894801]: Updating mesh.937               
[ INFO] [1593087488.908647205, 1593060805.819205211]: Updating mesh.937               
[ INFO] [1593087488.958528304, 1593060805.920538275]: Updating mesh.937               
[ INFO] [1593087489.009889644, 1593060806.021936363]: Updating mesh.937               
[ INFO] [1593087489.050381413, 1593060806.104500390]: Updating mesh.937               
[ INFO] [1593087489.102521483, 1593060806.208294955]: Updating mesh.937               
[ INFO] [1593087489.153089557, 1593060806.309775703]: Updating mesh.937               
[ INFO] [1593087489.204630500, 1593060806.411901659]: Updating mesh.937               
[ INFO] [1593087489.255213564, 1593060806.513206207]: Updating mesh.937               
[ INFO] [1593087489.306072190, 1593060806.614289558]: Updating mesh.937               
[ INFO] [1593087489.355806243, 1593060806.715153125]: Updating mesh.937               
[ INFO] [1593087489.406480719, 1593060806.816926758]: Updating mesh.937               
[ INFO] [1593087489.457696220, 1593060806.918355536]: Updating mesh.937               
[ INFO] [1593087489.508047801, 1593060807.019547240]: Updating mesh.937               
[ INFO] [1593087489.558095748, 1593060807.120368770]: Updating mesh.937               
[ INFO] [1593087489.609530587, 1593060807.221920445]: Updating mesh.937               
[ INFO] [1593087489.653041420, 1593060807.308943829]: Updating mesh.937               
[ INFO] [1593087489.703894279, 1593060807.410030688]: Updating mesh.937               
[ INFO] [1593087489.755800473, 1593060807.514289385]: Updating mesh.937               
[ INFO] [1593087489.805797496, 1593060807.615125703]: Updating mesh.937               
[ INFO] [1593087489.856511929, 1593060807.715958009]: Updating mesh.937               
[ INFO] [1593087489.907667624, 1593060807.817675980]: Updating mesh.937               
[ INFO] [1593087489.958006607, 1593060807.918666686]: Updating mesh.937               
[ INFO] [1593087490.008516190, 1593060808.019533207]: Updating mesh.937               
[ INFO] [1593087490.051155014, 1593060808.103928667]: Updating mesh.937               
[ INFO] [1593087490.103577663, 1593060808.209012459]: Updating mesh.937               
[ INFO] [1593087490.153380067, 1593060808.309944148]: Updating mesh.937               
[ INFO] [1593087490.203351560, 1593060808.410997752]: Updating mesh.937               
[ INFO] [1593087490.254597359, 1593060808.512074488]: Updating mesh.937               
[ INFO] [1593087490.307484375, 1593060808.618203799]: Updating mesh.937               
[ INFO] [1593087490.357880788, 1593060808.719177736]: Updating mesh.937               
[ INFO] [1593087490.408494499, 1593060808.820631920]: Updating mesh.937               
[ INFO] [1593087490.459046355, 1593060808.921747677]: Updating mesh.937               
[ INFO] [1593087490.501211099, 1593060809.004537110]: Updating mesh.937               
[ INFO] [1593087490.550928724, 1593060809.105447435]: Updating mesh.937               
[ INFO] [1593087490.602578056, 1593060809.207532492]: Updating mesh.937               
[ INFO] [1593087490.652391899, 1593060809.309034428]: Updating mesh.937               
[ INFO] [1593087490.702964499, 1593060809.410039801]: Updating mesh.937               
[ INFO] [1593087490.757584190, 1593060809.511100271]: Updating mesh.937               
[ INFO] [1593087490.804900776, 1593060809.612122339]: Updating mesh.937               
[ INFO] [1593087490.856610628, 1593060809.715885391]: Updating mesh.937               
[ INFO] [1593087490.906782039, 1593060809.816775843]: Updating mesh.937               
[ INFO] [1593087490.957927126, 1593060809.918178888]: Updating mesh.937               
[ INFO] [1593087491.007764375, 1593060810.018969492]: Updating mesh.937               
[ INFO] [1593087491.058997337, 1593060810.120423004]: Updating mesh.937               
[ INFO] [1593087491.101919564, 1593060810.206928112]: Updating mesh.937               
[ INFO] [1593087491.152544505, 1593060810.308278381]: Updating mesh.937               
[ INFO] [1593087491.202941581, 1593060810.409178518]: Updating mesh.937               
[ INFO] [1593087491.254175023, 1593060810.510256911]: Updating mesh.937               
[ INFO] [1593087491.305043848, 1593060810.611862486]: Updating mesh.937               
[ INFO] [1593087491.356220756, 1593060810.715454731]: Updating mesh.937               
[ INFO] [1593087491.406406952, 1593060810.816251738]: Updating mesh.937               
[ INFO] [1593087491.457295693, 1593060810.918274020]: Updating mesh.937               
[ INFO] [1593087491.509262330, 1593060811.022197446]: Updating mesh.937               
[ INFO] [1593087491.550396098, 1593060811.103635652]: Updating mesh.937               
[ INFO] [1593087491.601988169, 1593060811.206334244]: Updating mesh.937               
 [RUNNING]  Bag Time: 1593060811.293223   Duration: 9.890178 / 9.896937               
Done.
[player-1] process has finished cleanly
log file: /home/dszhang/.ros/log/ea3a07da-b6dd-11ea-82b1-b46921c40905/player-1*.log

**Comment by alandszhang** [comment]
Problem solved. Thanks.

**Comment by name8997** [comment]
i have same issue, what is the solution?

**Comment by jeaninevbrr** [comment]
@alandszhang Same problem here! How did you solve it?

**Comment by songanz** [comment]
@alandszhang Same problem! How did you solve it?

**Comment by Zhangppppp** [comment]
i have same issue,How did you solve it?Thanks.

**Comment by prmehta24** [comment]
> 

Hi @alandszhang , I am having a similar issue using an a rosbag generated by an Intel Realsense camera. I have rgb and depth topics, and I see messages mentioning the mesh is being updated, but the mesh array remains empty. How did you solve your issue?
