### ISSUE TITLE
"catkin_simple" problem

### ISSUE THREAD

**Issue by gaotao19890725** [MIT-SPARK/Kimera-Semantics#36]
Dear ToniRV,  thanks you for your great job! 
I do the simulation according to your suggestion, but the following error occurs:

Errors     << kimera_semantics:cmake /home/gaotao/data/catkin_ws/logs/kimera_semantics/build.cmake.001.log
CMake Error at /home/gaotao/data/catkin_ws/src/Kimera-Semantics/kimera_semantics/CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin_simple.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "catkin_simple", but CMake did not find one.

  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.

cd /home/gaotao/data/catkin_ws/build/kimera_semantics; catkin build --get-env kimera_semantics | catkin env -si  /usr/bin/cmake /home/gaotao/data/catkin_ws/src/Kimera-Semantics/kimera_semantics --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/gaotao/data/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/gaotao/data/catkin_ws/install -DCMAKE_BUILD_TYPE=Release; cd -

can you give me some suggestions about it, thanks a million.

**Comment by ToniRV** [comment]
Hi @gaotao19890725, sorry for the late answer, but you just need to `git clone https://github.com/catkin/catkin_simple`
into your catkin_ws/src .
