### ISSUE TITLE
Is it possible to run Euroc dataset with Kimera-Semantics?

### ISSUE THREAD

**Issue by jqk-68** [MIT-SPARK/Kimera-Semantics#42]
Dear Antoni,
First of all, I have to say that I am a huge fan of your work and Kimera project. I have spent this couple of days  read your articles and worked with Kimera. It encouraged me to try to run Euroc by combined Kimera-VIO and Kimera-Sematics.
Could you give me some thought to deal with that problem?

**Comment by ToniRV** [comment]
Hi @jqk-68!
I have just updated the Readme in #44, have a look at this [section](https://github.com/MIT-SPARK/Kimera-Semantics#with-kimera-vio).
Let me know if you find any problem!
