### ISSUE TITLE
I can't download the kimera_semantics_demo.bag

### ISSUE THREAD

**Issue by calmelo** [MIT-SPARK/Kimera-Semantics#52]
I can't download the kimera_semantics_demo.bag. Can you share me with other ways? Maybe email? 269537259@qq.com. Or how can I download it? Thanks very much.

**Comment by ToniRV** [comment]
@calmelo does this link work for you? https://drive.google.com/file/d/1SG8cfJ6JEfY2PGXcxDPAMYzCcGBEh4Qq/view
