### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by Viky397** [MIT-SPARK/Kimera-Semantics#59]
Hi all! When I `catkin build kimera_semantics_ros`, 14/15 packages build, but the last package throws the following error. Any help is appreciated, thank you!

![image](https://user-images.githubusercontent.com/48597425/108600901-ab6ff900-7367-11eb-846c-22eb373cb329.png)

**Comment by FPSychotic** [comment]
I posted I think a similar error in the ROS wrapper git, take a look there

**Comment by Viky397** [comment]
Were you able to solve it?

**Comment by FPSychotic** [comment]
No , I didn't but I didn't try again
