### ISSUE TITLE
ros kinetic

### ISSUE THREAD

**Issue by wolf943134497** [MIT-SPARK/Kimera-Semantics#6]
Hi @ToniRV   Thanks for your great works!
My ros version is kinetic, something error when catkin_make the package. Does the package support ros kinetic?  I'm not very familiar with ROS 
thanks!

**Comment by ToniRV** [comment]
Hi @wolf943134497! Thanks!  It should work as well in Kinetic.
If you send your error as well I might be able to help.
Also, I would recommend not to use `catkin_make` but `catkin build` as suggested in the Readme.

**Comment by wolf943134497** [comment]
@ToniRV   Thanks for your suggestion! catkin build works!   Wonder why catkin_make can not work.package.xml and cmakelist file should change a little?   I usually use catkin_make to build the specified package.

**Comment by ToniRV** [comment]
Not sure what might have gone wrong with `catkin_make` but I would strongly suggest to use `catkin build`. Thanks for reporting the issue!
