### ISSUE TITLE
Error when running roslaunch kimera_semantics_ros kimera_semantics.launch play_bag:=true

### ISSUE THREAD

**Issue by mohammad-h-b** [MIT-SPARK/Kimera-Semantics#60]
Hi,
When I run `roslaunch kimera_semantics_ros kimera_semantics.launch play_bag:=true` I get these errors:

![27](https://user-images.githubusercontent.com/43095906/108654626-153af080-7497-11eb-961e-d521e7345b74.png)

And the result in rviz is like this:

![28](https://user-images.githubusercontent.com/43095906/108654645-2552d000-7497-11eb-8f73-a4ec76990120.png)

**Comment by ToniRV** [comment]
Can you try this #61 and see if it solves the issue?

**Comment by mohammad-h-b** [comment]
Great! It solved the issue. Thank you!
