### ISSUE TITLE
Why can't I achieve the effect of the paper after rebuilding the map?

### ISSUE THREAD

**Issue by HongLouyemeng** [MIT-SPARK/Kimera-Semantics#74]
![image](https://user-images.githubusercontent.com/48181529/142034466-960a007e-b6f3-4033-b285-bc66a7af9dfa.png)
The above is the result of my reconstruction using "uhumans_12" data, and the following is the result in the paper:
Is it the problem of data set or parameters? Can you give me some suggestions?
![image](https://user-images.githubusercontent.com/48181529/142034865-3e0a3544-9e08-4899-b698-41554d3b85ac.png)

**Comment by ToniRV** [comment]
@HongLouyemeng the figure in the paper is from the uHumans1 dataset: http://mit.edu/sparklab/datasets/uHumans/

https://drive.google.com/file/d/1c6vAHmCd9onycQnCVnw6rK5mNPJ-dC3j/view?usp=sharing

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng the figure in the paper is from the uHumans1 dataset: http://mit.edu/sparklab/datasets/uHumans/
> 
> https://drive.google.com/file/d/1c6vAHmCd9onycQnCVnw6rK5mNPJ-dC3j/view?usp=sharing

Thank you for your reply
