### ISSUE TITLE
Poor Performance on Euroc 3D reconstruction ?

### ISSUE THREAD

**Issue by caiodataopshouse** [MIT-SPARK/Kimera-Semantics#90]
Hello.

I was able to run the tesse segmentation demo, and the 3D reconstruction worked exactly like on your video. But when I tried using the Euroc V1 easy, the 3D reconstruction was very poor. The VIO output (odometer and per mesh frame) seems right, but the 3D reconstruction looks like this: 

![Screenshot 2024-06-28 at 10 09 39](https://github.com/MIT-SPARK/Kimera-Semantics/assets/124146045/053f6f8b-215c-4583-b924-ae28d2333867)

I had to make some changes on the launch files for both the Tesse and Euroc to work.. mainly I change the sensor_frame_id (it was cam_left, and I changed to base_link) I also had to change the tf coming from the VIO because it was giving a transform from base_link to odom, and I think voxblox expects a world frame, so I changed the "odom_drame_id" to world. 

As you can see the 3D reconstruction is very bad. and doest look like the YouTube video I saw from you guys. There also seems to be a 90 degree rotation from what the per mesh frame gives.

**Comment by caiodataopshouse** [comment]
Im referring to this reconstruct when I compare https://youtu.be/-5XxXRABXJs

**Comment by caiodataopshouse** [comment]
Sorry the problem was that I was using base_link as sensor_frame on the semantics euroc launch. I still need to set odom_frame_id  from "odom" to "world" so it works out of the box in the vio euroc launch! Maybe this requires a PR ?

**Comment by avrunito** [comment]
Hi, I am trying to reproduce the steps that you made, but I'm unable to. Could you please post the launch files that you used? Are you using ROS Noetic or another version?
